# Generated by Django 5.1.6 on 2025-03-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_film',
            name='director',
            field=models.CharField(default='NoName', max_length=50, verbose_name='Режисер'),
        ),
    ]
